describe("application_helper", fn()
  describe("strip_title_heading", fn()
    test("removes the first # Title line", fn()
      let result = strip_title_heading("# Title\n\nSome body text")
      assert_eq(result, "Some body text")
    end)

    test("keeps ## Title (not a first-level heading)", fn()
      let result = strip_title_heading("# Title\n\n## Section\n\nBody")
      assert(result.contains("## Section"))
    end)

    test("returns full body when no # Title prefix", fn()
      let result = strip_title_heading("Some body text")
      assert_eq(result, "Some body text")
    end)

    test("drops leading blank line after # Title", fn()
      let result = strip_title_heading("# Title\n\n\nBody")
      assert_not(result.starts_with("\n"))
    end)
  end)

  describe("truncate_text", fn()
    test("returns text unchanged when shorter than length", fn()
      let result = truncate_text("Hello", 10, "...")
      assert_eq(result, "Hello")
    end)

    test("truncates with ellipsis when text is longer", fn()
      let result = truncate_text("Hello World", 8, "...")
      assert_eq(result, "Hello...")
    end)

    test("uses custom suffix", fn()
      let result = truncate_text("Hello World", 8, ">>")
      assert_eq(result, "Hello >>")
    end)
  end)

  describe("capitalize", fn()
    test("capitalizes first letter", fn()
      assert_eq(capitalize("hello"), "Hello")
    end)

    test("leaves already capitalized string unchanged", fn()
      assert_eq(capitalize("Hello"), "Hello")
    end)

    test("returns empty string for empty input", fn()
      assert_eq(capitalize(""), "")
    end)
  end)

  describe("_is_safe_link_url", fn()
    test("accepts http and https", fn()
      assert(_is_safe_link_url("http://example.com"))
      assert(_is_safe_link_url("https://example.com"))
    end)

    test("accepts mailto", fn()
      assert(_is_safe_link_url("mailto:test@example.com"))
    end)

    test("accepts absolute paths", fn()
      assert(_is_safe_link_url("/some/path"))
      assert(_is_safe_link_url("/"))
    end)

    test("accepts fragment and query", fn()
      assert(_is_safe_link_url("#fragment"))
      assert(_is_safe_link_url("?query=value"))
    end)

    test("rejects javascript URLs", fn()
      assert(not _is_safe_link_url("javascript:alert(1)"))
      assert(not _is_safe_link_url("javascript:void(0)"))
    end)

    test("rejects data URLs", fn()
      assert(not _is_safe_link_url("data:text/html,<script>alert(1)</script>"))
    end)

    test("treats relative URLs without scheme as safe", fn()
      assert(_is_safe_link_url("some/path"))
    end)
  end)

  describe("link_to", fn()
    test("generates anchor tag with safe URL", fn()
      let result = link_to("Click", "/some/path")
      assert(result.contains("<a"))
      assert(result.contains("href=\"/some/path\""))
      assert(result.contains(">Click<"))
    end)

    test("escapes link text", fn()
      let result = link_to("<script>", "/path")
      assert(result.contains("&lt;script&gt;"))
    end)
  end)

  describe("pluralize", fn()
    test("singular for count of 1", fn()
      assert_eq(pluralize(1, "item", "items"), "1 item")
    end)

    test("plural for count not 1", fn()
      assert_eq(pluralize(3, "item", "items"), "3 items")
    end)

    test("zero uses plural", fn()
      assert_eq(pluralize(0, "item", "items"), "0 items")
    end)
  end)

  describe("pluralize_simple", fn()
    test("adds s for plural", fn()
      assert_eq(pluralize_simple(2, "task"), "2 tasks")
    end)

    test("no s for singular", fn()
      assert_eq(pluralize_simple(1, "task"), "1 task")
    end)
  end)

  describe("round_dollar", fn()
    test("rounds to two decimal places", fn()
      assert_eq(round_dollar(10.456), 10.46)
      assert_eq(round_dollar(10.454), 10.45)
    end)

    test("keeps exact cents unchanged", fn()
      assert_eq(round_dollar(10.50), 10.50)
    end)
  end)

  describe("format_date", fn()
    test("formats ISO timestamp", fn()
      assert_eq(format_date("2026-05-13T10:30:00Z"), "13 May 2026")
    end)

    test("returns empty for nil", fn()
      assert_eq(format_date(nil), "")
    end)

    test("returns empty for empty string", fn()
      assert_eq(format_date(""), "")
    end)

    test("returns empty for unparseable input", fn()
      assert_eq(format_date("not-a-date"), "")
    end)
  end)
end)